name: floodsense
services:
- name: backend
  github:
    branch: master
    deploy_on_push: true
    repo: John-Akech/SSDFLOODSENSEFLOODPREDICTION
  dockerfile_path: backend/Dockerfile
  source_dir: /
  http_port: 8000
  routes:
  - path: /api/v1
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VAPID_PUBLIC_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VAPID_PRIVATE_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: VAPID_SUBJECT
    scope: RUN_AND_BUILD_TIME
    value: mailto:admin@floodsense.org
  - key: SAR_SERVICE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${sar-detection.PUBLIC_URL}
  - key: CORS_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: https://floodsense-app-6a3uy.ondigitalocean.app,https://floodsense.org,http://localhost:3000,http://localhost:5173,http://localhost:80,http://localhost
- name: frontend
  github:
    branch: master
    deploy_on_push: true
    repo: John-Akech/SSDFLOODSENSEFLOODPREDICTION
  dockerfile_path: frontend/Dockerfile
  source_dir: frontend
  http_port: 80
  routes:
  - path: /
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: VITE_API_URL
    scope: BUILD_TIME
    value: ${backend.PUBLIC_URL}/api/v1
  - key: VITE_SAR_URL
    scope: BUILD_TIME
    value: ${sar-detection.PUBLIC_URL}
  - key: VITE_VAPID_PUBLIC_KEY
    scope: BUILD_TIME
    value: ${backend.VAPID_PUBLIC_KEY}
- name: sar-detection
  github:
    branch: master
    deploy_on_push: true
    repo: John-Akech/SSDFLOODSENSEFLOODPREDICTION
  dockerfile_path: ee-fastapi/Dockerfile
  source_dir: ee-fastapi
  http_port: 8080
  routes:
  - path: /sar
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: GEE_PROJECT_ID
    scope: RUN_TIME
    value: ace-connection-474712-p1
  - key: GEE_SERVICE_ACCOUNT_KEY
    scope: RUN_TIME
    type: SECRET
databases:
- name: db
  engine: PG
  version: "15"
  production: false
